---
title: "R Notebook"
output: html_notebook
---

# Initialize environment

## Initialize R Suite project

```{r, rsuite_init, eval=FALSE}
# Detect proper script_path (you cannot use args yet as they are build with tools in set_env.r)
script_path <- (function() {
  args <- commandArgs(trailingOnly = FALSE)
  script_path <- dirname(sub("--file=", "", args[grep("--file=", args)]))
  if (!length(script_path)) {
    return("R")
  }
  if (grepl("darwin", R.version$os)) {
    base <- gsub("~\\+~", " ", base) # on MacOS ~+~ in path denotes whitespace
  }
  return(normalizePath(script_path))
})()

# Setting .libPaths() to point to libs folder
source(file.path("..", script_path, "set_env.R"), chdir = T)

config <- load_config()
args <- args_parser()
```

## Intialize Spark connection

```{r, spark_connect}
library(sparklyr)
library(arrow)

conf <- list()
conf$`sparklyr.cores.local` <- 2
conf$`sparklyr.shell.driver-memory` <- "2G"
conf$spark.memory.fraction <- 0.9

sc <- sparklyr::spark_connect(master = "spark://spark-master:7077", 
                              config = conf)
```
